// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpmonFlowKey struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Dport uint16
	Pad   uint16
}

type tcpmonFlowVal struct {
	_           structs.HostLayout
	Bytes       uint64
	SrttUs      uint64
	SrttSamples uint64
	LastSeenNs  uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcpmonMapFlows           = "flows"
	tcpmonProgTcpProbeHook   = "tcp_probe_hook"
	tcpmonProgTcpSendmsgHook = "tcp_sendmsg_hook"
	tcpmonVarPortMax         = "port_max"
	tcpmonVarPortMin         = "port_min"
)

// loadTcpmon returns the embedded CollectionSpec for tcpmon.
func loadTcpmon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpmonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpmon: %w", err)
	}

	return spec, err
}

// loadTcpmonObjects loads tcpmon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpmonObjects
//	*tcpmonPrograms
//	*tcpmonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpmonObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpmon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpmonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpmonSpecs struct {
	tcpmonProgramSpecs
	tcpmonMapSpecs
	tcpmonVariableSpecs
}

// tcpmonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpmonProgramSpecs struct {
	TcpProbeHook   *ebpf.ProgramSpec `ebpf:"tcp_probe_hook"`
	TcpSendmsgHook *ebpf.ProgramSpec `ebpf:"tcp_sendmsg_hook"`
}

// tcpmonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpmonMapSpecs struct {
	Flows *ebpf.MapSpec `ebpf:"flows"`
}

// tcpmonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpmonVariableSpecs struct {
	PortMax *ebpf.VariableSpec `ebpf:"port_max"`
	PortMin *ebpf.VariableSpec `ebpf:"port_min"`
}

// tcpmonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpmonObjects struct {
	tcpmonPrograms
	tcpmonMaps
	tcpmonVariables
}

func (o *tcpmonObjects) Close() error {
	return _TcpmonClose(
		&o.tcpmonPrograms,
		&o.tcpmonMaps,
	)
}

// tcpmonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpmonMaps struct {
	Flows *ebpf.Map `ebpf:"flows"`
}

func (m *tcpmonMaps) Close() error {
	return _TcpmonClose(
		m.Flows,
	)
}

// tcpmonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpmonVariables struct {
	PortMax *ebpf.Variable `ebpf:"port_max"`
	PortMin *ebpf.Variable `ebpf:"port_min"`
}

// tcpmonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpmonPrograms struct {
	TcpProbeHook   *ebpf.Program `ebpf:"tcp_probe_hook"`
	TcpSendmsgHook *ebpf.Program `ebpf:"tcp_sendmsg_hook"`
}

func (p *tcpmonPrograms) Close() error {
	return _TcpmonClose(
		p.TcpProbeHook,
		p.TcpSendmsgHook,
	)
}

func _TcpmonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpmon_bpfel.o
var _TcpmonBytes []byte
