#!/usr/bin/env python3
"""Apply bounded assessment corrections to the saved long-form manuscript."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / "docs/publication/manuscript-before-revision.md"
text = source.read_text()
changes = {
    "and necessary and sufficient\n  payback conditions for fixed and remaining-work horizons": "and algebraic\n  payback conditions for fixed and remaining-work fluid surrogates",
    "for a single request under a 120 ms network delay latency placement is 65.4%\n  faster.": "for a single request under a 120 ms network delay latency placement has\n  65.4% higher throughput and 36.1% lower completion time.",
    "and 99.2% of an\n  application-level link-cost residual is queueing rather than network time.": "and, in a\n  separate synthetic loopback diagnostic, 99.2% of the application-level\n  link-cost residual is worker queueing.",
    "We distil these results into deployment guidelines and release the\n  runtime, an installable multi-device application, and all raw traces.": "We distil these results into deployment guidelines and provide a locally\n  auditable runtime, application and raw traces; public artifact access is\n  pending.",
    "Datacenter systems make such\nreconfiguration cheap": "Several GPU serving systems reduce\nreconfiguration overhead",
    "placement is 65.4% faster (4.00 vs 2.42 tokens/s).": "placement has 65.4% higher throughput (4.00 vs 2.42 tokens/s).",
    "them through concurrency, and necessary and sufficient payback conditions for\n  fixed and remaining-work horizons": "them through concurrency, and algebraic payback conditions for\n  fixed and remaining-work fluid surrogates",
    "Our contribution is their combination\nin one small, inspectable system with explicit replay accounting, and a\ncareful measurement of how they behave, and fail, in practice.": "Integration of these ingredients is also established in SpotServe, DynoPipe\nand FlexPipe. Our narrower contribution is an inspectable CPU runtime and an\nempirical account of whole-run losses, replay cost and misleading telemetry in\na small deployment; integration alone is not a novelty claim.",
    "pipeline boundaries dynamically between edge and cloud [@lin2026dynopipe]. These systems": "pipeline boundaries dynamically between edge and cloud [@lin2026dynopipe].\nDynoPipe jointly models workload, queueing, compute, network and transition\noverhead; its testbed combines RTX 3090 edge GPUs and an A40 cloud cluster.\nFlexPipe adjusts pipeline granularity to request patterns and preserves KV\nconsistency during refactoring in a fragmented GPU cluster [@lin2026flexpipe].\nThese systems",
    "bottleneck objective to matter. Shardwise's automatic mode applies this rule,\nusing the latency objective at $Q\\le1$ and the throughput objective otherwise.\nEvaluated with profile costs, (3) is an *ideal envelope*, not a guarantee on\nmeasured execution; Section 6.1 compares the two.": "bottleneck objective to matter. The historical two-worker automatic mode\nused latency at $Q\\le1$ and throughput otherwise; this is not a general rule\nfor larger pipelines. For nine uniform layers on three equal workers with\nunit remote-link costs, minimizing $B$ gives $B=4,P=11$, whose $Q=2$\nenvelope is 5.5. Using two active stages gives $B=5,P=10$ and envelope 5.\nThe revised runtime minimizes $\\max(B,P/Q)$ directly by bottleneck-cap\nsearch with a constrained sum DP. Its correctness is checked against 1,000\nexhaustive random instances. This implementation change has not been evaluated\nin the historical matrices. Equation (3) remains an ideal capacity bound,\nnot an achievable-throughput guarantee.",
    "The whole chain is priced because a generation change rebuilds request state\nthrough every layer, including layers whose owner does not change.": "The whole chain is priced because a generation change rebuilds request state\nthrough every layer, including layers whose owner does not change. In the\nhistorical implementation, $C$ is the configured profile context, not a sum\nover active requests. It does not explicitly account for concurrent histories,\nserialization or changing context lengths. The revised opt-in live-context\nforecast uses $F+pL\\sum_{r=1}^{Q} C_r$, where $C_r$ counts each prompt plus\naccepted output. This prices serial replay work; overlap, weight loading,\nserialization and orchestration still require measured calibration. Missing or\nstale live-context telemetry suppresses voluntary moves, while recovery is\nallowed.",
    "that is, if the tokens served in the remaining time after the transition exceed\nthose served without moving by the margin.": "that is, if the fluid service capacity after the transition exceeds the\nstay capacity by the stated relative margin. The two sides are surrogate\ncapacities, not actual completed work from a finite cohort.",
    "Condition (7) shows why small budgets suppress moves.": "Condition (7) characterizes this horizon-capped surrogate only. A finite\ncohort contains at most $R$ tokens; actual completion cannot exceed that\ncap, and concurrency changes as requests finish. For constant per-token\ncosts, a zero-margin finite-cohort makespan comparison is\n$T+Rj_n<Rj_c$. If a margin is applied to completion time, it must be defined\nthere, for example $(1+m)(T+Rj_n)<Rj_c$; it is not Equation (7).\nCondition (7) shows why small budgets suppress moves.",
    "2.419, a 65.4% advantage for latency placement; median completion is 8.012\nversus 12.531 s.": "2.419, a 65.4% throughput advantage for latency placement; median completion\nis 8.012 versus 12.531 s, a 36.1% reduction. The reverse comparison is a\n39.5% throughput loss from choosing throughput placement.",
    "safe default; for two or more overlapping requests the bottleneck objective\ngives a large gain in both throughput and completion time.": "useful internal baseline; for two overlapping requests on the tested two\nworkers, bottleneck placement improves these metrics. The arms activate\ndifferent amounts of compute. They do not establish a gain over a\nresource-matched single-model or replica server.",
    "The forecast is low by 76.2% and 29.2%.": "Measured disruption exceeds the forecast by 76.2% and 29.2%, respectively.\nEquivalently the forecast is 43.3% and 22.6% below measurement.",
    "without speculative decoding, and bottleneck placement when two or more\n   requests overlap.": "without speculative decoding. At larger concurrency compare the ideal\n   envelope $\\max(B,P/Q)$ rather than assuming $Q>1$ fills every pipeline.",
    "Profile-based forecasts were 29-76% low.": "Measured disruptions exceeded profile forecasts by 29-76%; the corresponding\n   forecast shortfalls were 23-43% of measured duration.",
    "Splitting a small language model across commodity machines pays off under two\nconditions: requests must overlap, so that pipeline stages have parallel work,\nor a machine must fail, so that adaptation preserves availability.": "The two-worker study identifies conditions under which objective choice and\nrecovery improve an internal runtime baseline. Request overlap permits\npipeline parallel work, and replay restores service after remote-worker loss\nwhen the survivor can hold the full model. Neither observation establishes\nthat splitting beats resource-matched replication or optimized unsplit serving.",
    "65.4% loss from the wrong one for a single delayed request": "39.5% throughput loss from the wrong one for a single delayed request",
    "renewing workloads and weak baselines can distort them. We release the\nruntime, the installable multi-device application and every raw trace so that\nthese results can be checked and extended.": "renewing workloads and weak baselines can distort them. The gate has no\ndemonstrated advantage over hysteresis in these small-repeat matrices. The\nlocal runtime, application and raw traces allow inspection; public repository\nand dataset access remain pending. Router/controller loss and survival when\nthe model does not fit a remaining worker are outside the recovery claim.",
}
for old, new in changes.items():
    if old not in text:
        raise RuntimeError(f"missing expected source phrase: {old[:80]}")
    text = text.replace(old, new)
(ROOT/"docs/publication/manuscript-revised.md").write_text(text)
(ROOT/"docs/paper/elsevier/manuscript.md").write_text(text)
print(f"Applied {len(changes)} assessment corrections")
