import csv,json,re,pathlib
p=pathlib.Path(__file__).parent;s=p/'sources'
cols=['work_id','title','year','venue','status','identifier','source_url','hardware_and_setup','granularity','runtime_repartition','migration_pricing','device_loss','headline_results','evidence_quotes_and_locations','verification_gaps']
rows=[]
def add(key,title,year,venue,ids,hardware,gran,run,price,loss,headline,quote,loc,pdf=None,status='PEER-REVIEWED'):
 url='https://doi.org/'+ids.split(';')[0] if ids.startswith('10.') else 'https://arxiv.org/abs/'+ids.split(';')[0].replace('arXiv:','')
 evidence='“'+quote+'” — '+loc if quote else 'UNVERIFIED exact sentence; publisher abstract/metadata only'
 if pdf and quote:
  raw=(s/(pdf+'-raw.txt')).read_text();raw=re.sub(r'(\w)-\s*\n\s*(\w)',r'\1\2',raw);norm=lambda x:re.sub(r'\s+',' ',x).strip()
  if norm(quote) not in norm(raw): evidence+='; normalized quotation match UNVERIFIED'
  else:
   page=norm(raw).find(norm(quote));needle=re.compile(re.escape(norm(quote)))
   for i,a in enumerate(raw.split('\f'),1):
    if norm(quote) in norm(a): evidence+='; PDF page '+str(i);break
 rows.append(dict(zip(cols,[key,title,year,venue,status,ids,url,hardware,gran,run,price,loss,headline,evidence,'One limited exact quotation per source; other extracted claims require additional sentence transcription. Full-text locators supplied in cells; unlocated fields marked UNVERIFIED.'])))
add('disco2025','DiSCo: Device-Server Collaborative LLM-based Text Streaming Services',2025,'Findings of ACL 2025','10.18653/v1/2025.findings-acl.734; arXiv identifier UNVERIFIED','§5.1 pp14264–65: server 4 A40 48GB; Pixel7Pro and Xiaomi14 device profiles; BLOOM560M/1.1B and Qwen1.5-0.5B; four production service traces. Physical phone end-to-end migration execution UNVERIFIED.','Whole request/device-server switch; heterogeneous models, not contiguous layer layout','Yes, request handover (§4.3)','§4.3 Eq4: remaining output × expected decode-cost savings must exceed migration overhead','UNVERIFIED device loss; migration is voluntary endpoint switching','§5/abstract: 6–78% mean and 11–52% tail TTFT reduction; up to83.6% cost reduction across heterogeneous service traces; not same-model exact replay benchmark','This formulation ensures that migration only occurs when the projected cost savings exceed the overhead of transferring control between endpoints.','§4.3 proceedings p14264 / PDF p5',pdf='disco')
add('star2026','STAR: Decode-Phase Rescheduling for LLM Inference',2026,'HPDC 2026','10.1145/3806645.3807813; arXiv:2510.13668v2','§6.1: real single-server 4 RTX4090D (1prefill/3decode) and single-server8 H800 (2prefill/6decode); DeepSeekR1-Distill-Qwen7B/Qwen3-14B, ShareGPT/Alpaca, long outputs; 256-instance study simulated','Request/KV-cache migration across decode replicas','Yes, decode requests; not layer relayout','§5.2/Alg1 line20: filter requests whose predicted remaining steps cannot amortize migration cost; current/future load weighted by predicted length','UNVERIFIED node-loss recovery','Abstract/v2: up to75.1% P99TPOT reduction and2.63x goodput; maxima across experiments, not a consumer pipeline comparison','In this paper, we propose STAR, a decode rescheduling system powered by length prediction to anticipate future workloads.','Abstract',pdf='star')
add('e2llm2026','E2LLM: Towards Efficient LLM Serving in Heterogeneous Edge/Fog Environments',2026,'arXiv preprint','arXiv:2606.03770v3','§4.1/Table2 PDFp7: eight physical devices: RTX5070 12GB; RTX3060M6GB;2M2Max32GB;2M1 16GB;2DGXSpark128GB limited to12GB model memory;1GbpsLAN measured920Mbps. GPT-oss20b/Qwen3-30B-A3B Q4_K_M;36 configurations','Contiguous layer ranges, replicas, prefill/decode grouping','Offline profile/planning; live active-request layer movement UNVERIFIED','UNVERIFIED live migration pricing; optimizer minimizes latency/finishing time','UNVERIFIED','§4.3/conclusion: up to2x decode throughput and >50% lower wait versus adapted Splitwise and own HexGen2-objective planner; explicitly not a faithful port of HexGen2','In the experiments, we use eight devices, as shown in Table 2, ranging from embedded to desktop devices.','§4.1',pdf='e2llm-v3',status='PREPRINT; latest v3 23Aug2026; accepted venue UNVERIFIED')
add('flowspec2025','FlowSpec: Continuous Pipelined Speculative Decoding for Efficient Distributed LLM Inference',2025,'arXiv preprint; latest revision2026','arXiv:2507.02620v3','§V.A:5JetsonOrinNano8GB unified memory/1GbpsLAN; Llama2Chat7B/13B,Vicuna1.3 7B/13B;EAGLE2;6datasets20samples each128generated tokens;temperatures0/1','Layer pipeline plus speculative token tree','Online draft-tree adaptation; physical layer repartition UNVERIFIED','UNVERIFIED','UNVERIFIED','Abstract/v3:1.37–1.73x speedup over pipeline/speculative baselines; sparse-request/speculation setup, not ordinary multi-request decoder PP','We evaluate FlowSpec on a real-world testbed with other baselines.','Abstract',pdf='flowspec-v3',status='PREPRINT; latest v3 10Jan2026; accepted venue UNVERIFIED')
add('helix2025','Helix: Serving Large Language Models over Heterogeneous GPUs and Network via Max-Flow',2025,'ASPLOS 2025','10.1145/3669940.3707215; arXiv:2406.01566','§6.2 proceedingsp594: real24GoogleCloud single-GPU nodes(4A100/8L4/12T4),10Gbps;geo24node and42node7GPU-type studies SIMULATED. Llama30B/70B FP16;AzureConversation trace;10min offline/30min online','Layer segments, overlapping placement, max-flow request routing','Online routing; placement MILP offline; live repartition UNVERIFIED','UNVERIFIED active state-migration payback','UNVERIFIED','§6.3 real24node Llama30B:2.14x offline/2.07x online throughput versus Swarm;32%prompt/12%decode latency reduction. Abstract2.7x includes simulated clusters','The latter two setups are performed in simulation.','§6.2',pdf='helix')
add('hexgen2024','HexGen: Generative Inference of Large Language Model over Heterogeneous Environment',2024,'ICML 2024 / PMLR235','arXiv:2311.11514','Evaluation: real homogeneous16A10040GB on2AWS p4d;heterogeneous58FluidStack GPUs(3090Ti/A5000/A6000/A40) in Iceland/Norway/Nevada/Illinois;full$65.04/h versusAWS$65.54/h;half30GPU$29.6/h;Llama2-70B','Asymmetric pipeline layers plus tensor groups','Placement search; live request-preserving layer migration UNVERIFIED','Dollar-budget deployment optimization; finite-horizon migration gate UNVERIFIED','UNVERIFIED','Abstract: up to2.3x lower latency deadlines or4x greater request rate at same budget; different hardware across budget-matched alternatives','We conduct an extensive evaluation to verify the efficiency of HEXGEN by serving the state-of-the-art LLAMA- 2 (70B) model.','Abstract',pdf='hexgen')
add('hexgen22025','HexGen-2: Disaggregated Generative Inference of LLMs in Heterogeneous Environment',2025,'ICLR 2025','arXiv:2502.07903','§5.1: realRunPod baseline8H10080GB $29.52/h;5heterogeneous H100/A100/L40/A6000 deployments, first4samebudget fifth70%budget;OPT30B/Llama2-70B','PP+TP+prefill/decode split; max-flow KV routing','Placement optimization; active layer repartition UNVERIFIED','Deployment dollar budget; cross-phase KV-transfer costs; remaining-request payback UNVERIFIED','UNVERIFIED','OfficialICLR abstract:up to2.0x/mean1.3x throughput,1.5x average latency reduction,samebudget;comparable performance30%cheaper','Towards this end, we introduce HEXGEN-2, a distributed system for efficient and economical LLM serving on heterogeneous GPUs following the disaggregated paradigm.','Abstract',pdf='hexgen2')
add('thunderserve2025','ThunderServe: High-performance and Cost-efficient LLM Serving in Cloud Environments',2025,'MLSys 2025','arXiv:2502.09334','§5.1: real32VastAI GPUs:2x4A6000,2x4A5000,1x8A40,2x4RTX3090Ti,$13.542/h;separate homogeneous in-house comparison;models/workload exact mapping to maxima UNVERIFIED','TP/PP groups plus prefill/decode replica roles','§4 lightweight role rescheduling without weight reload; fixes model partition/group layout during this adaptation','Avoids weight-reload cost; explicit remaining-horizon payback UNVERIFIED','Abstract/§5.3 node-failure adaptation; exact fault trial count UNVERIFIED','Abstract:up to2.1x/avg1.7x throughput and2.5x/avg1.5x latency-deadline improvement at matched price budget;baselines HexGen/DistServe/vLLM across different hardware','In this work, we propose ThunderServe, a high-performance and cost-efficient LLM serving system for heterogeneous cloud environments.','Abstract',pdf='thunderserve')
add('cachegen2024','CacheGen: KV Cache Compression and Streaming for Fast Large Language Model Serving',2024,'SIGCOMM 2024','10.1145/3651890.3672274; arXiv:2310.07240','§7.1: real4A40 server384GBRAM/2XeonGold6130;Mistral7B,Llama34B/70B;long contexts up to32k;controlled bandwidth','KV-cache chunk compression/streaming','Runtime chunk encoding/transfer versus text recomputation; not physical layer repartition','§6.2 predicts next-chunk bandwidth from previous chunk, chooses KVbitstream or token-text recompute','UNVERIFIED node-loss recovery','Abstract:3.5–4.3x KV size reduction and3.2–3.7x context fetching/processing speedup; compression plus dynamic bandwidth, not model-worker failover','The use of different quantizations at different layers is inspired by the observation of heterogeneous loss sensitivity (§5.1.2).','§5.2',pdf='cachegen')
add('pipeinfer2024','PipeInfer: Accelerating LLM Inference using Asynchronous Pipelined Speculation',2024,'SC 2024','10.1109/SC41406.2024.00046; arXiv:2407.11798v2','§V.A/TableII: realCPU clusters A8nodes dualXeonE5-2650/128GB/1GbE;B13heterogeneous Optiplexi5/i7/Xeon8–128GB/1GbE;C32dualXeonGold6140/384GB/100GbpsIB;large decoder models','Layer pipeline with asynchronous speculative sequences','Scheduling adapts speculative work; physical layer migration UNVERIFIED','UNVERIFIED','Resilience to heterogeneous throughput discussed; actual lost-node recovery UNVERIFIED','Abstract:up to2.15x generation speed versus standard speculative decoding; single-request speculative pipeline setup','The head node then evaluates the first few layers according to the allocated split.','Implementation',pdf='pipeinfer')
add('aipcfleet2026','Pre-Compiled Pipeline Shards for Distributed LLM Inference on Intel AI PC Fleets',2026,'arXiv preprint','arXiv:2608.19147','§6:3physical Windows11 WiFi802.11ax PCs:2ASUSZenbookS14 CoreUltra7-258V/Arc140V32GB;1HPOmniBookX16 CoreUltraX7-358H/ArcB39032GB. Separate4IntelTiberCloud nodes run Llama3.1-70B INT4.100ms/hop WAN study SIMULATED','Precompiled contiguous layer pipeline/OpenVINO;multi-stream microbatching','Static shard placement; live migration UNVERIFIED','UNVERIFIED','UNVERIFIED','§6 multi-stream table:8B three-node/3stream64.67tokens/s=2.64x mono-A;2stream50.55tokens/s=2.06x. Aggregate throughput, not per-user speed;WAN relaycompression separate','but that metric conflated actual TCP latency with the time spent waiting for the remote worker to compute.','Instrumentation discussion (exact excerpt, not a whole sentence)',pdf='aipcfleet',status='PREPRINT; 19Aug2026')
add('dlora2024','dLoRA: Dynamically Orchestrating Requests and Adapters for LoRA LLM Serving',2024,'OSDI 2024','https://www.usenix.org/conference/osdi24/presentation/wu-bingyang','§7.1:real4nodesx8A80080GB=32GPUs;128CPUcores/2048GBhost each;200GbpsIB','LoRA adapter and request co-migration; not base-model layer movement','Yes, request+adapter scheduling','Credit-based merge/unmerge batching; migration accounting; exact finite-token payback UNVERIFIED','UNVERIFIED','Abstract:up to57.9x throughput versusvLLM and26.0x versusHFPEFT;1.8x lowerlatency versusS-LoRA;multi-adapter workload, not edge PP','To address the second problem, we propose a request- adapter co-migration technique.','Introduction',pdf='dlora')
rows[-1]['source_url']=rows[-1]['identifier']
add('pdserve2024','P/D-Serve: Serving Disaggregated Large Language Model at Scale',2024,'arXiv preprint','arXiv:2408.08147','Abstract/§4:tensofthousandsproductionNPUs over8months;detailed test configurations/modelidentity UNVERIFIED','Prefill/decode replica groups; KV state transfer/RDMA','Runtime groupscale andinstanceplacement; live layer-boundary migration UNVERIFIED','KV-transfer/interphase traffic accounting; finite-horizon gate UNVERIFIED','Instance auto-recovery/replacement; otherregions continue afterregionloss(§3); exact active-request preservation UNVERIFIED','Abstract:6.7x throughput improvement;60%E2E42%TTFT SLO improvement;46%lessKVtransferdelay;production aggregated maxima, not a controlled commoditycluster comparison','Once the region-level failures occur, other regions continuously serve the requests without service interruption.','Recovery without Interruption',pdf='pdserve',status='PREPRINT; accepted venue UNVERIFIED')
add('banaserve2026','BanaServe: Unified KV Cache and Dynamic Module Migration for Balancing Disaggregated LLM Serving in AI Infrastructure',2026,'Software: Practice and Experience','10.1002/spe.70054; arXiv:2510.13223','§5.1:13B Llama/OPT,Alpaca/LongBench,Poisson1–20RPS;physical GPU model/nodecount UNVERIFIED in inspected preprint','Dynamic layer/module and attention migration; unified KV storage','Yes, module allocation/migration(Alg2)','Load imbalance threshold andmigrationoverhead; explicit remaining-work payback UNVERIFIED','UNVERIFIED','Abstract:1.2–3.9x throughput versusvLLM;1.1–2.8x versusDistServe;setup maxima acrossshort/longcontexts;hardware disclosure gap','We implement BanaServe and evaluate it with 13B-parameter models on production workload traces.','Introduction',pdf='banaserve')
add('matching2025','A Matching Game for Distributed Inference of Large Language Models in Edge Computing',2025,'IEEE Open Journal of the Communications Society6:3795–3805','10.1109/OJCOMS.2025.3561605','Publisherabstract:heterogeneous device layer allocation;simulation/small vision-language testbed mentioned in indexed extracts;exact physical hardware/count UNVERIFIED','Layer matching with pipeline-bubble/latency effects','UNVERIFIED live repartition','UNVERIFIED state-migration pricing','UNVERIFIED','Headline number UNVERIFIED; do not use search-snippet ~10% without metric/setup verification','','Publisher abstract')
add('jiang2026pipeline','Edge Inference for Large Language Models With Pipeline Parallelism and Batching',2026,'IEEE Transactions on Communications74:8390–8406','10.1109/TCOMM.2026.3686718','Publisher abstract: heterogeneous compute/memory/link models; simulation evaluation; real-device testbed UNVERIFIED','Layer PP, batching and wireless bandwidth allocation','Online request scheduling; active physical layer migration UNVERIFIED','UNVERIFIED','UNVERIFIED','Publisher abstract:up to42.1%latencyreduction; simulation setup/baseband exactbaseline UNVERIFIED','','Publisher abstract')
add('edgeatp2026','EdgeATP: An adaptive tensor parallelism framework for scalable and efficient transformer inference on edge clusters',2026,'Journal of Systems Architecture177','10.1016/j.sysarc.2026.103861','Publisher abstract:real multi-device homogeneous/heterogeneous testbed;hardware model/count UNVERIFIED;fulltext access restricted','Tensor partition; DRL adaptation undercompute/linkchanges','Yes, adaptive tensor allocation; exact state transition protocol UNVERIFIED','UNVERIFIED','UNVERIFIED','Publisher abstract:up to3.15x latencyperformance;44.9%overexistingmethods;exact baseline/model/setup mapping UNVERIFIED','We implement and evaluate EdgeATP on a real-world multi-device edge testbed, including both homogeneous and heterogeneous configurations.','Abstract')
with (p/'root-rows.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=cols);w.writeheader();w.writerows(rows)
# Build BibTeX only from saved primary metadata; absent DOI is omitted, never guessed.
out=[]
for f in sorted(s.glob('*metadata.json')):
 d=json.loads(f.read_text());key=f.stem.replace('-metadata','')
 if 'citation_title' in d:
  title=d['citation_title'][0];authors=d.get('citation_author',[]);year=d['citation_date'][0][:4]
  if key=='e2llm2026':authors=['Le, Truong-Thanh','La, Hoang-Loc','Taherkordi, Amir','Eliassen, Frank','Ha, Phuong Hoai','Guan, Peiyuan']
  ent={'title':title,'author':' and '.join(authors),'year':year,'eprint':d['arxiv'],'archivePrefix':'arXiv','primaryClass':'cs.DC','url':'https://arxiv.org/abs/'+d['arxiv'],'note':'Author list verified against arXiv metadata; publication status and identifier in related-work-table.csv. arXiv year is first posting.'}
  ent.pop('primaryClass') # classification not independently checked
  if d.get('citation_doi'):ent['doi']=d['citation_doi'][0]
  typ='misc'
 else:
  ent={'title':d['title'][0],'author':' and '.join((a.get('family','')+', '+a.get('given','')).strip(', ') for a in d.get('author',[])),'year':str(d.get('published',d.get('published-print',d.get('published-online')))['date-parts'][0][0]),'doi':d['DOI'],'url':'https://doi.org/'+d['DOI'],'note':'Metadata verified against Crossref on 2026-10-06'}
  typ='article' if d['type']=='journal-article' else 'inproceedings';ent['journal' if typ=='article' else 'booktitle']=d.get('container-title',['UNVERIFIED'])[0]
  for k in ['volume','issue','page']:
   if k in d:ent[{'issue':'number','page':'pages'}.get(k,k)]=str(d[k]).replace('-','--') if k=='page' else str(d[k])
 out.append('@'+typ+'{'+key+',\n'+',\n'.join('  '+k+' = {'+v+'}' for k,v in ent.items())+'\n}\n')
out.append((s/'disco-publisher.bib').read_text())
out.append('''@inproceedings{star2026,
 title={STAR: Decode-Phase Rescheduling for LLM Inference},
 author={Wang, Zhibin and Hong, Zetao and Li, Xue and Wang, Zibo and Li, Shipeng and Meng, Qingkai and Wang, Qing and Huan, Chengying and Gu, Rong and Zhong, Sheng and Tian, Chen},
 booktitle={Proceedings of the 35th International Symposium on High-Performance Parallel and Distributed Computing},
 year={2026}, doi={10.1145/3806645.3807813}, eprint={2510.13668}, archivePrefix={arXiv},
 url={https://arxiv.org/abs/2510.13668}, note={Verified against final HPDC metadata printed in arXiv v2 PDF, page1; title changed from ARES in v1}
}
@inproceedings{dlora2024,
 title={dLoRA: Dynamically Orchestrating Requests and Adapters for LoRA LLM Serving},
 author={Wu, Bingyang and Zhu, Ruidong and Zhang, Zili and Sun, Peng and Liu, Xuanzhe and Jin, Xin},
 booktitle={18th USENIX Symposium on Operating Systems Design and Implementation (OSDI24)},
 year={2024}, pages={911--927}, publisher={USENIX Association},
 url={https://www.usenix.org/conference/osdi24/presentation/wu-bingyang}, note={Verified USENIX proceedings; no DOI asserted}
}
''')
(p/'root-references.bib').write_text('\n'.join(out))
print('Wrote',len(rows),'root rows and',len(out),'BibTeX groups')
for r in rows:
 if 'match UNVERIFIED' in r['evidence_quotes_and_locations']:print('QUOTE REVIEW:',r['work_id'])
